# Generated by Django 5.0 on 2024-04-03 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_additionalinformation_additional_information_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product_detail',
        ),
    ]
