# Generated by Django 5.0 on 2024-04-03 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_cart_product_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.productdetail'),
        ),
    ]
