# Generated by Django 5.0 on 2024-04-18 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_cart_cart_subtotals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_subtotals',
        ),
    ]
