# Generated by Django 5.0 on 2024-04-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_cart_cart_subtotals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
